### PR TITLE
Freeze Option before/after showing photos

### PR DESCRIPTION
**Pull request by ky0n**
this is for #369 

I tested the implementation through the gui and wrote a test for cli both with one photo.
let me know your feedback

### CODE REVIEW

**Review by McPringle — APPROVED** [review]
Thank you very much for implementing this feature! You help is highly appreciated.

**Comment by McPringle** [comment]
Where does the photo came from? Is it you photo and which license does apply?

**Comment by McPringle** [comment]
On GitHub actions it seems to pass but on my local machine your test fails: `AssertionFailedError: expected: <193> but was: <0>`

**Comment by McPringle** [comment]
I fixed it and made the test independent of the system locale.

**Comment by ky0n** [comment]
> Where does the photo came from? Is it you photo and which license does apply?

It's not my photo. I downloaded it from [here](https://github.com/ianare/exif-samples/blob/master/jpg/Canon_PowerShot_S40.jpg)

apparently it has wikimedia commons license, but it's not mentioned specifically here in the readme https://github.com/ianare/exif-samples/tree/master/jpg

**Comment by ky0n** [comment]
> I fixed it and made the test independent of the system locale.

ah great, i didn't thought about that

**Comment by McPringle** [comment]
> It's not my photo. I downloaded it from [here](https://github.com/ianare/exif-samples/blob/master/jpg/Canon_PowerShot_S40.jpg)
> 
> apparently it has wikimedia commons license, but it's not mentioned specifically here in the readme https://github.com/ianare/exif-samples/tree/master/jpg

Just to be sure I removed the photo and replaced it with a photo from my own library (`src/test/resources/photo/bikeride.jpg`). I took that photo on the bike ride I use for testing (`src/test/resources/gpx/bikeride.gpx`), so the GPS coordinates and date/time (EXIF metadata) are correct.

**Pull request merged**
