### PR TITLE
#625 add plugin maven-publish for create jar.  

### PR DESCRIPTION
**Pull request by onixred**
add plugin for publish jar file for use gpx-animator as lib.

### CODE REVIEW

**Review by McPringle — CHANGES_REQUESTED** [review]
I see one problem with this configuration: It publishes two JAR files. It should only publish the generated artefact `gpx-animator-1.9.0-SNAPSHOT.jar` and let Maven (or Gradle etc.) handle the dependencies. The fat JAR `gpx-animator-1.9.0-SNAPSHOT-all.jar` should **not** be published.

**Comment by onixred** [comment]
> I see one problem with this configuration: It publishes two JAR files. It should only publish the generated artefact `gpx-animator-1.9.0-SNAPSHOT.jar` and let Maven (or Gradle etc.) handle the dependencies. The fat JAR `gpx-animator-1.9.0-SNAPSHOT-all.jar` should **not** be published.

please give me a hint why the fat jar  is being collected

**Comment by McPringle** [comment]
> @McPringle please give me a hint why the fat jar is being collected

I don't know anything about the Maven Publish plugin. But I guess that it just takes all JAR files from the `build/lib` directory by default. You could check the docs if it supports configuring an include or exclude.

**Comment by onixred** [comment]
@McPringle  I add skip shadow jar for publication.

**Review by McPringle — APPROVED** [review]

**Comment by McPringle** [comment]
Thanks for your adjustment, I think the result is much better this way.

**Pull request merged**
