### PR TITLE
begin and end animation of photo on marker

### PR DESCRIPTION
**Pull request by ky0n**
this is for ticket #376. 
It works with bikeride.gpx and bikeride.jpg 🙂
not sure if the check for the marker beeing in the frameImage is needed

### CODE REVIEW

**Review by McPringle — CHANGES_REQUESTED** [review]
I rendered a video using the files `bikeride.gpx` and `bikeride.jpg`. This was the result (screenshot second 36):

image

It's hard to see, but the final photo is not in the center any more. Here you can see the final photo rendered without your PR:

image

The photo is perfectly centered. The animation should start at the actual point on the map, that is what you did. But you must recalculate the position of each animation frame to finish up with the final photo centered. Otherwise the photo might not fit on screen. Here is an example where I rendered the same video in Full HD:

image

The final photo must be in the center to fit on the screen.

**Comment by ky0n** [comment]
okay, thanks for figuring this out. I will try to fix it.

**Comment by ky0n** [comment]
Could you check again pls? 

It still looks weird with the HD-rendered video, the marker seems to be outside of the animation. But the picture is inside it.

**Review by McPringle — APPROVED** [review]
That looks perfect! Thank you very much. For the problem with the track not fitting in some cases I created a new issue #638. I'll take a look at it within the next few days.

**Pull request merged**
