### PR TITLE
#648 add manual and setting jitpack

### PR DESCRIPTION
**Pull request by onixred**
1. add manual
2. add setting file

### CODE REVIEW

**Comment by onixred** [comment]
Hi maybe is it MR  merge?

**Comment by onixred** [comment]
hello @McPringle maybe see my  pull request/

**Review by McPringle — CHANGES_REQUESTED** [review]
Sorry for my late reply, the last few months I took a sabbatical and rode my bicycle through the whole US. Then you very much for your contribution. I would like one change: Please move the information of using GPX Animator as a library to the `README.md` file, possibly between the sections "Test" and "Related projects".

**Comment by onixred** [comment]
fixed

**Review by McPringle — CHANGES_REQUESTED** [review]
Sorry, I think you misunderstood me. Please move the *contents* from the `LIB.md` into the `README.MD` file. It contains all the information about compiling, running, and using GPX-Animator.

**Comment by onixred** [comment]
ok I deleted LIB.md and rework README.MD

**Review by McPringle — APPROVED** [review]

**Comment by McPringle** [comment]
Thank you very much for your contribution!

**Pull request merged**
